   spring:
    h2.console:
      enabled: true
      path: '/console'
    datasource:
          url: 'jdbc:h2:file:/home/hepsko/projekty/todo-list/todo-db'
    jpa:
      hibernate:
        ddl-auto: validate




